<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <version>${pm.version.maven-jar-plugin}</version>
    <configuration>
        <excludes>
            <exclude>**/doc-files/</exclude>
        </excludes>
    </configuration>
</plugin>