<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${pm.version.maven-compiler-plugin}</version>
    <configuration>
        <source>${maven.compiler.source}</source>
        <target>${maven.compiler.target}</target>
        <optimize>true</optimize>
        <encoding>${project.build.sourceEncoding}</encoding>
    </configuration>
</plugin>